# Generated by Django 4.2.21 on 2025-05-25 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tryhello", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
    ]
