# Generated by Django 4.2.21 on 2025-05-25 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tryhello", "0002_course_is_active"),
    ]

    operations = [
        migrations.CreateModel(
            name="TestTable",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
            ],
            options={"db_table": "Test_Table", "ordering": ["-name"],},
        ),
    ]
